CREATE TABLE [dbo].[offline_usr_details](
	[usr_id] [varchar](9) NOT NULL,
	[usr_profile_pic] [text] NULL,
	[usr_about] [text] NULL,
	[usr_name] [text] NULL,
	[usr_gender] [varchar](3) NULL,
	[usr_dob_day] [int] NULL,
	[usr_dob_month] [int] NULL,
	[usr_dob_year] [int] NULL,
	[usr_place_of_birth] [text] NULL,
	[usr_marital_status] [varchar](3) NULL,
	[usr_no_children] [varchar](3) NULL,
	[usr_chaildren_staying_with] [varchar](3) NULL,
	[usr_diet] [varchar](3) NULL,
	[usr_smoking_habit] [varchar](3) NULL,
	[usr_drinking_habit] [varchar](3) NULL,
	[usr_more_basic_details] [text] NULL,
	[usr_body_type] [varchar](3) NULL,
	[usr_body_complexion] [varchar](3) NULL,
	[usr_physically_chalanged] [varchar](3) NULL,
	[usr_height] [varchar](3) NULL,
	[usr_weight] [text] NULL,
	[usr_blood_group] [varchar](3) NULL,
	[usr_more_physical_sttributes] [text] NULL,
	[usr_mother_tongue] [varchar](3) NULL,
	[usr_religion] [varchar](3) NULL,
	[usr_caste] [varchar](3) NULL,
	[usr_subcaste] [varchar](3) NULL,
	[usr_mangalik] [varchar](3) NULL,
	[usr_gotra] [varchar](3) NULL,
	[usr_sunsign] [varchar](3) NULL,
	[usr_moonsign] [varchar](3) NULL,
	[usr_nakshatra] [varchar](3) NULL,
	[usr_horoscope_match] [varchar](3) NULL,
	[usr_more_religious_details] [text] NULL,
	[usr_education_category] [varchar](3) NULL,
	[usr_education_details] [text] NULL,
	[usr_profession] [varchar](3) NULL,
	[usr_professiona_details] [text] NULL,
	[usr_incme] [varchar](3) NULL,
	[usr_more_occupation_details] [text] NULL,
	[usr_family_values] [varchar](3) NULL,
	[usr_family_type] [varchar](3) NULL,
	[usr_fmaily_status] [varchar](3) NULL,
	[usr_family_origin] [text] NULL,
	[usr_fathers_occupation] [varchar](3) NULL,
	[usr_fathers_occupation_details] [text] NULL,
	[usr_mothers_occupation] [varchar](3) NULL,
	[usr_mothers_occupation_details] [text] NULL,
	[usr_no_brothers] [text] NULL,
	[usr_no_brothers_married] [text] NULL,
	[usr_no_sisters] [text] NULL,
	[usr_no_sisters_married] [text] NULL,
	[usr_more_family_details] [text] NULL,
	[usr_country] [varchar](3) NULL,
	[usr_state] [varchar](3) NULL,
	[usr_citizenship] [text] NULL,
	[usr_city] [varchar](3) NULL,
	[usr_present_address] [text] NULL,
	[usr_permanent_address] [text] NULL,
	[usr_mobile_number] [text] NULL,
	[usr_other_contect] [text] NULL,
	[usr_more_contact_details] [text] NULL,
 CONSTRAINT [PK_offline_usr_details] PRIMARY KEY CLUSTERED 
(
	[usr_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]